### ISSUE TITLE
Missing function delete_by_size in stomataobjects

### ISSUE THREAD

**Issue by bpavie** [TeamMacLean/stomatameasurer#1]
Dear,

I tried to use your tool by it looks like the function `delete_by_size()` which is called in the file `stomataobjects.py` in the function `object_filter` is missing, is it coming from another library?
Best,

**Comment by danmaclean** [comment]
I agree, it is missing. Thanks for the heads up. Looks like this was something I intended to implement for general use but forgot about. I'll try a quick fix very soon.

**Comment by danmaclean** [comment]
I've added this function and it _should_ work as expected now. There is a new version of the package on PyPI https://pypi.org/project/stomatadetector/0.0.7.dev0/ built off the delbysize branch. Check that branch's readme for info on slightly different filter syntax.

Hope it works ok for you.
